#!/bin/bash

CMD=`basename $0`

show_help()
{
    echo "Usage: $CMD <FILM_TITLE>"
}

if [ $# -lt 1 ]; then
    echo "Fail! -- Expecting at least 1 argument! ==> $@"
    show_help
    exit 1
fi

if [ -z "`which curl`" ]; then
    echo "Fail! -- Requires \"curl\""
    echo "Hint: sudo aptitude install curl"
    exit 1
fi

QUERY=`echo $@ | tr '[:upper:]' '[:lower:]'`
DOMAIN='www.imdb.com'
#URL="http://$DOMAIN/find?q=`echo $QUERY | tr ' ' '+'`"
URL="http://$DOMAIN/search/title?title=`echo $QUERY | sed 's/ /%20/g'`&title_type=feature"
echo ""
echo "Extracting ratings URL from.. ==> $URL"

EXTRACTED_URL=`curl $URL                                                            | # download HTML using curl
        tr '[:upper:]' '[:lower:]'                                                  | # convert to lowercase
        tr -d '\n'                                                                  | # remove carriage returns
        sed 's#</#\n</#g'                                                           | # tokenize by HTML tag
        grep "/title/.* title=\".*$QUERY.*\""                                       | # locate lines with "/title/" and "title=\"$QUERY\""
        sed 's#^.*href="\([^\"]*\)" title="\([^\"]*\) (\([0-9?]*\))".*$#\3|\2|\1#g' | # capture film year, title, and ratings URL
        sort | uniq`
echo ""
echo -e "Downloading ratings for:\n`echo \"$EXTRACTED_URL\" | cut -d'|' -f1,2 | xargs -I@ echo - @`"

echo ""
while read LINE; do
    FILM_YEAR=`echo $LINE | cut -d'|' -f1`
    FILM_NAME=`echo $LINE | cut -d'|' -f2`
    FILM_URL="http://$DOMAIN`echo $LINE | cut -d'|' -f3`"
    echo -n "\"$FILM_NAME ($FILM_YEAR)\" ==> "
    CRITICS_RATING=`curl -s $FILM_URL | # download HTML using curl
            tr -d '\n'                | # remove carriage returns
            sed 's#</#\n</#g'         | # tokenize by HTML tag
            grep "ratingValue\">"     | # locate lines with "ratingValue\">"
            tr '\n' @                 | # tokenize by line
            cut -d@ -f1               | # isolate first instance
            sed 's/^.*>//g'`            # remove everything before ">"
    if [ -n "$CRITICS_RATING" ]; then
        echo "Ratings: $CRITICS_RATING/10"
    else
        echo "n/a"
    fi
done <<< "$EXTRACTED_URL"
